/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CIndexRouteImport } from './routes/c.index'
import { Route as CSlugRouteImport } from './routes/c.$slug'

const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CIndexRoute = CIndexRouteImport.update({
  id: '/c/',
  path: '/c/',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/merchant': typeof MerchantRoute
  '/c/$slug': typeof CSlugRoute
  '/c/': typeof CIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/merchant': typeof MerchantRoute
  '/c/$slug': typeof CSlugRoute
  '/c': typeof CIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/merchant': typeof MerchantRoute
  '/c/$slug': typeof CSlugRoute
  '/c/': typeof CIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/merchant' | '/c/$slug' | '/c/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/merchant' | '/c/$slug' | '/c'
  id: '__root__' | '/' | '/merchant' | '/c/$slug' | '/c/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MerchantRoute: typeof MerchantRoute
  CSlugRoute: typeof CSlugRoute
  CIndexRoute: typeof CIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/': {
      id: '/c/'
      path: '/c'
      fullPath: '/c/'
      preLoaderRoute: typeof CIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MerchantRoute: MerchantRoute,
  CSlugRoute: CSlugRoute,
  CIndexRoute: CIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
